const fs = require("fs");
const path = require("path");
const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins");

/**
 * Scopes Android cleartext traffic to the self-hosted relay (audit M5, M8).
 *
 * Why a config plugin at all: `android.usesCleartextTraffic` in app.json is an
 * inert key. It is absent from @expo/config-types' schema and nothing in
 * @expo/config-plugins ever reads it off the config — it appears only as a
 * TypeScript type describing an AndroidManifest XML attribute. The cleartext
 * setting shipped purely because the generated android/ tree is committed, so
 * app.json and the manifest stated the same intent twice, with only one of them
 * load-bearing, and a `prebuild --clean` would have silently dropped it.
 *
 * This plugin is now the single place that intent lives. It writes the resource
 * and points the manifest at it, so a clean prebuild reproduces exactly what is
 * committed under android/ instead of regressing to unscoped cleartext.
 *
 * The scoping rationale — and the RFC1918 limitation of Android's
 * network-security-config grammar — is documented in the XML itself below.
 */

const RES_PATH = "app/src/main/res/xml/network_security_config.xml";

/**
 * Canonical contents of res/xml/network_security_config.xml.
 * The committed copy under android/ is generated from this constant; keep them
 * byte-identical (plugins/__checks__/release-config.check.js asserts it).
 */
const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Cleartext policy for PantryRun (audit M5) - CLOSED.

  This replaces a bare android:usesCleartextTraffic="true" on <application>,
  which was a single global switch with no way to say anything about *which*
  hosts. Cleartext is now DENIED by default, mirroring the iOS ATS posture
  (NSAllowsArbitraryLoads=false), with the narrow exceptions below.

  Why these exceptions, and only these
  Android's grammar has no CIDR, and includeSubdomains matches a DNS *suffix*
  while the octet that varies in a private IP is the suffix - so an RFC1918
  range is not expressible without ~65k entries. iOS gets this for free via
  NSAllowsLocalNetworking; Android does not. What IS expressible:

    localhost / 127.0.0.1  a relay on the device itself
    10.0.2.2 / 10.0.3.2    the Android-emulator aliases for the host machine
    *.home.arpa            the IETF-reserved home-network domain (RFC 8375),
                           which is what a router's DNS should hand out

  NOT ".local" - Android's OkHttp path does not resolve mDNS without
  NsdManager, so a .local entry would be decorative rather than useful.

  What this breaks, deliberately
  A self-hoster connecting to a bare LAN IP over ws:// (e.g.
  ws://192.168.1.50:8080) will no longer connect. React Native's WebSocket goes
  through OkHttp, which consults
  NetworkSecurityPolicy.isCleartextTrafficPermitted(host), so that traffic is
  now refused. This is intended: that config sends the family's routing
  metadata across the LAN in the clear, and it was previously the documented
  recommendation.

  docs/self-host-security.md was migrated in the same change and now tells LAN
  self-hosters to use either a hostname their router resolves (a home.arpa
  name) or wss://. Anyone already on a bare-IP relay must move to one of those.
  This is a breaking change for that group and is called out in the release
  notes.

  This file is generated by plugins/withNetworkSecurityConfig.js on prebuild.
  Edit the plugin, not this file. plugins/__checks__/release-config.check.js
  asserts the two match byte for byte.
-->
<network-security-config>

  <!-- Default: no cleartext to anyone. Mirrors iOS ATS. -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>

  <!-- Loopback and the emulator host aliases: a relay running on this device
       or on the dev machine behind an emulator. Never leaves the host. -->
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">127.0.0.1</domain>
    <domain includeSubdomains="false">10.0.2.2</domain>
    <domain includeSubdomains="false">10.0.3.2</domain>
  </domain-config>

  <!-- RFC 8375 home-network domain. A router handing out relay.home.arpa gives
       self-hosters a name this file can actually express, which a bare
       192.168.x.x address cannot be. -->
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="true">home.arpa</domain>
  </domain-config>

  <!-- Public endpoints the app calls: HTTPS only, no downgrade, and no
       inheritance of the cleartext exceptions above. -->
  <domain-config cleartextTrafficPermitted="false">
    <!-- Invite / applink host and its subdomains. -->
    <domain includeSubdomains="true">groceryapp.app</domain>
    <!-- USDA FoodData Central product lookups. -->
    <domain includeSubdomains="true">api.nal.usda.gov</domain>
    <!-- Open Food Facts product lookups. -->
    <domain includeSubdomains="true">openfoodfacts.org</domain>
  </domain-config>

</network-security-config>
`;

/**
 * Points <application> at the resource and drops the app-wide cleartext switch.
 * Exported so the release-config check can drive it without running a prebuild.
 */
function setNetworkSecurityConfig(androidManifest) {
  const application = androidManifest.manifest.application?.find((a) =>
    a.$?.["android:name"]?.endsWith(".MainApplication")
  );
  if (!application) {
    throw new Error("AndroidManifest.xml is missing the MainApplication element");
  }
  application.$["android:networkSecurityConfig"] = "@xml/network_security_config";
  // The whole point of the resource is that this blanket attribute goes away;
  // leaving it would keep permitting cleartext to every host on API < 24.
  delete application.$["android:usesCleartextTraffic"];
  return androidManifest;
}

function withNetworkSecurityConfig(config) {
  config = withAndroidManifest(config, (cfg) => {
    cfg.modResults = setNetworkSecurityConfig(cfg.modResults);
    return cfg;
  });

  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const dest = path.join(cfg.modRequest.platformProjectRoot, RES_PATH);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, NETWORK_SECURITY_CONFIG_XML);
      return cfg;
    },
  ]);
}

module.exports = withNetworkSecurityConfig;
module.exports.setNetworkSecurityConfig = setNetworkSecurityConfig;
module.exports.NETWORK_SECURITY_CONFIG_XML = NETWORK_SECURITY_CONFIG_XML;
module.exports.RES_PATH = RES_PATH;
